### ISSUE TITLE
Ensure visitor is a BMC member before confirming booking

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#1]
Following discussion at the last DWMH meeting and subsequently at the BMC, we need to ensure that visitors are validated as BMC members before they are allowed to book accommodation. presently they are asked to enter a BMC membership number or a club name but this is not validated.

The requirement is that the BMC number is validated against the BMC online database of members.

The details of this are not yet defined. For example:
* is every single booking restricted in this way? There was a discussion about Scottish visitors; bookings are also intended to be entered by an administrator 'on behalf' of someone - is this also restricted?
* how are expired memberships to be handled? or for that matter new ones, or newly renewed ones, which have not (yet) reached the database?
* do we transition the history to this new system - how are past bookings to be maintained if the membership number proves to be invalid?

**Comment by asimshah** [comment]
Following my own advice, I plan to split this into multiple separate issues!
1. See #3 for a verification discussion
