### ISSUE TITLE
"My Bookings"

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#10]
"I am also suggesting a ‘My bookings’ feature where you can access booking status and key code."

(from booking app document - 30Jul2015)

**Comment by asimshah** [comment]
Mark often gets queries like ‘am I still booked’ due to the potentially lengthy time lags.

**Comment by asimshah** [comment]
What does the My Booking feature actually do?

**Comment by mikebattye** [comment]
I think it shows that the booking is still on the system - the dates and number in party (people do forget this) - whether paid or not.
These are the things that folks call Mark about.


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
Does that mean you only include bookings that are not past the occupancy date? or do you show all bookings back in time? or is there some other selection criteria?

**Comment by mikebattye** [comment]
I think this is meant to cover future bookings only.

While I think about it could it show the key code (if the booking is paid)?
