### ISSUE TITLE
Differential Pricing

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#12]
If at all possible we should have the possibility of differential pricing (e.g. weekend/weekdays, summer/winter). It is not necessary to have a day/evening rate. This can be negotiated with the booking sec who could then block the hut as in present system. 

(from booking app document - 30Jul2015)

**Comment by asimshah** [comment]
In what way does differential pricing connect with blocking the hut?

**Comment by mikebattye** [comment]
Sorry, not clear about the question. Aren't they independent?


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
If you read the paragraph, the last sentence "This can be negotiated with the booking sec who could then block the hut as in present system." does not make any sense to me: what is being negotiated and why? The system either does or does not implement differential pricing. How does blocking the hut have any effect on differential pricing?

I think you have something in mind which I know nothing at all about! Perhaps you block the hut for some reason ... I don't know

**Comment by mikebattye** [comment]
What I am trying to say is that blocking/closing the hut is a means by which the booking sec can make bookings outside the system (which is what I mean by a ‘manual’ booking). Mark has occasionally done this in the past. The disadvantage is mainly from a recording point of view as the system would then have no record of occupancy, etc. it also means that other ‘admin’ people can’t see what the hut is being used for - though a note field could be used to indicate the reason.
