### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#14]
Make it easier to find a booking if a query comes in (presumably without a reference number or even possibly not being sure about the date!)

(from booking app document - 30Jul2015)

**Comment by asimshah** [comment]
So what do we search by?

**Comment by mikebattye** [comment]
Last name - membership number - date of occupancy (commencing)? Surely that will find most (all) bookings?


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
new system includes a search feature
