### ISSUE TITLE
Edit Booking

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#15]
Editing is not possible under the present system – has to be cancelled and remade.

(from booking app document - 30Jul2015)

**Comment by asimshah** [comment]
Does this mean editing to change the number of beds/rooms or also the days? Remember that with the weekends having to be whole hut bookings, the booking form is not easy to visualise - sometimes one might be able to add a day (at the beginning or at the end) and sometimes not.

Plus there is the complication of a weekend, whole hut, booking: can this be extended back or forwards and does that mean the whole hut has to be available?

**Comment by mikebattye** [comment]
I take your point. Perhaps we just have to stick with cancel and remake as in the present system.


Sent from my Samsung device

-------- Original message --------
