### ISSUE TITLE
Terms & Conditions

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#17]
Under the current app you can’t access the T&Cs before checking the accept box.

(from booking app document - 3oJul2015)

**Comment by asimshah** [comment]
The reason for this is that there is no easy way to insert a link to a page that is guaranteed to always lead to the T&Cs.

Plus the booking needs to be saved in some way so that the visitor can return to it. But if they choose to then leave the site, there is no way for the server to know that this booking needs to be removed.

Is there way that we can arrange for the T&Cs to be checked *before* any actual booking process starts?

**Comment by mikebattye** [comment]
I’ll try to work through your latest messages tomorrow morning. We can talk then

Mike

**Comment by mikebattye** [comment]
Could the t&c not be part of the booking app - a page that administration sets up at the start? It would have to be written to cover all eventualities but that should be possible.


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
There are two separate issues:

1. The text of the T&C. If it is never, *ever* going to edited, then yes it could somehow be part of the booking app. But if it is editable then there has to be some way of editing it. The existing app does have a concept of editable templates (for email and so on) but this is "outside" the webframe model, i.e. they are not pages and, for example, are not backed up. I would like to find a solution that is better than this (so that I do not have to manually look after this type of content - as I have to at present). Not that I know yet what would be a good solution ...
2. The second issue is whether the member is effectively encouraged to go off and read the T&Cs having already started making a booking (and therefore creating the problem I referred to above: save the booking before going to the T&C's? and, if so, when to cancel it if the visitor then leaves? - browser's do not understand the concept of "leaving" something since you are supposed to be able to hop from site to site within the same session.

**Comment by mikebattye** [comment]
Would it be sufficient (‘legally') to view and agree to T&Cs before starting the booking process? This would keep the process in the website. If you didn’t agree for some reason then the app wouldn’t be opened.

**Comment by asimshah** [comment]
T&C link is now implemented.
