### ISSUE TITLE
Using the Administrator account

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#18]
It is quite hard to customise the Administrator account - not impossible but hard. This is because it has to remain valid under all circumstances so that access to the features of Webframe are not locked out permanently.

Consequently, it will not be possible to associate a BMC number with the admin account. In effect this means that no booking should be made using the admin account.

This is a little paradoxical given that the admin account is supposed, in theory, to be able to do anything!

Of course, it perfectly possible to make any member an admin by adding them to the Administrators group, so to some extent the issue is merely a technical one.

But it does reinforce the idea that we should not habitually use the built-in Administrator account where a suitably privileged member account would do the job.

**Comment by mikebattye** [comment]
Agreed.


Sent from my Samsung device

-------- Original message --------
