### ISSUE TITLE
Advance Booking Time window

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#19]
The current, live, app automatically makes an extra day available every night, a year out. This is how the DWH booking has been working but it is "locked" into the code.
One could imagine a variety of ways in which other huts might operate. But perhaps they are all exactly the same.
Perhaps some alternative(s) need to be considered that allow some more flexibility. Bear in mind, for example, that if you decided to wind up the DWH at some point in the future you would perhaps need to come in every day and block that day as it opened up - not terribly easy to manage!

**Comment by mikebattye** [comment]
Does that need to apply to Admin? Could we not separate the display of availability depending on group? So for all members it is 12 mths (or whatever) whereas Admin can see further? Just a thought…

 

 

Regards, Mike

**Comment by asimshah** [comment]
I don't understand the point you are trying to make. if you want the admin to "see" further ahead, then this is a separate feature altogether from my original point (and needs its own specification ...)

**Comment by mikebattye** [comment]
I think I am arguing for more flexibility. There are occasions when you might want to alter the time window, or as you say, other huts might allow 18months ahead for example.
