### ISSUE TITLE
Booking Process Rules

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#20]
1. Only logged in visitors will be allowed to book (i.e. they will have to have registered on a previous occasion and be valid members).
1. For members in a special group, name TBA, booking will be allowed without validation of the BMC membership number - note, for such members there need be no BMC member recorded.
1. for all others, the BMC number will be revalidated (online at the BMC). If this fails, booking will not be allowed.
1. if the booking is starting within 28 days of today, then payment will be required through the payment gateway. If payment is declined, or fails, the booking will be abandoned.
1. If the booking starts later than 28 days from today, then the booking will be allowed and option provided to pay through the gateway. However, payment will ne be required. In these cases payment may also be made by selecting the booking via the "My Bookings" feature at some later time.

**Comment by asimshah** [comment]
In the light of the above rules and assuming that the Sage pay gateway is implemented, is there any need for the immediate booking windows - same day or the 7 day one for "Privileged" members? All members could book right up to today, provided the payment is successfully made?

**Comment by mikebattye** [comment]
Yes. The idea should be that any registered member can see all availability and book same day.
