### ISSUE TITLE
Room options

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#23]
Would it be clearer if this "1 Room for 4, 4 Beds" was "1 Room for 4 plus 4 beds"?

**Comment by mikebattye** [comment]
And if I book for 12 people why have the choose options stage at all?

**Comment by asimshah** [comment]
I will make this change. And I plan to skip the choose options step in all cases where there is only one choice available for whatever reason.

**Comment by asimshah** [comment]
Should be fixed in the next version
