### ISSUE TITLE
Under 18s

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#28]
1.       If under18s are present, booking must start at  > N + 14 regardless of any other circumstances.
2.       The BS must approve at > N otherwise the booking will be cancelled for non payment.
3.       If approval occurs too late for the first reminder, it is not sent.
4.       The final reminder is always sent (as approval has to be > N)

If someone tries to make an U18 booking at <N + 14 will they will get a message to contact the BS? If so, can the BS do anything to make the booking happen? 

I think it should be made clear (booking instructions, app itself?) that U18s only needs to be checked if they are not accompanied by parent/guardian.

**Comment by asimshah** [comment]
1. No. They will be informed that they need to booking N + 14 days in advance if there are any 18s present.
2. You can add whatever information you like on the site. The site does not, in general, try to provide instructions as people go along - not in this case nor in any other case.
