### ISSUE TITLE
Select days to block

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#30]
Should the day select box show booked days as it does in the Booking page?

![capture1](https://cloud.githubusercontent.com/assets/11847651/11333580/9d5fb342-91c6-11e5-90c2-9d8ca1cae680.JPG)

**Comment by asimshah** [comment]
No is does not - there is a lot of synchronisation required and I really did not think it worth repeating here.

**Comment by mikebattye** [comment]
Leave it as it is - as only administration will use this feature, and mostly on a decent size screen, it is workable.


Regards,Mike
Sent from my S5 phone

-------- Original message --------
