### ISSUE TITLE
Weekend whole hut requirement consequence

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#31]
Noticed as part of my testing that if you book a span of days which include a weekend you have to take the whole hut for the whole period. Not sure if or how this can be avoided, but if so we will have to explain to punters to make separate bookings for the weekdays if less than 12 in the party.

**Comment by asimshah** [comment]
That is correct. Splitting the request up into up to 3 separate 'sub' bookings is hard to do in the UI and has all sorts of complications elsewhere.
