### ISSUE TITLE
Part completed booking showing in Calendar

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#34]
I started a booking for 13 July but because of issue 'Login confusion' quit the browser before completing the booking. However it is now showing as part booked in the Calendar.

**Comment by mikebattye** [comment]
I have tested this is more detail.

I made a booking for 14 July (as Ben Gosling). Completed up to enter name. Clicked Sage pay. Returned (correctly, I assume) that address not completed. Quit broswer. Looking as Admin shows that this day is part booked on Calendar and in Occupancy Report  but there is no booking shown under View Bookings. 

Hope that is now reproducible.

**Comment by asimshah** [comment]
is this still a problem without the gateway running?

**Comment by mikebattye** [comment]
I can't reproduce the sequence anymore if that is what you are asking. There is no longer a Sage pay option.

**Comment by asimshah** [comment]
Ok, so please close it.
