### ISSUE TITLE
Mark as not Paid

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#36]
What happens if a booking has been marked as paid and therefore confirmed but then marked as not paid? Maybe not a frequent issue but possibly could arise because of an admin error. According to the log when I tried this with Aug15/003 she still got the notification email on the correct date. Presumably admin needs to cancel the booking to stop this happening. Probably not worth redesigning the flow as long as Booking Sec is aware that this will happen.
![image](https://cloud.githubusercontent.com/assets/11847651/16770094/3c9edd88-4843-11e6-80c0-7397be889af9.png)

**Comment by asimshah** [comment]
You need to consult your state diagrams: in the context of no payment gateway and a booking that is being set to not paid (from paid), what state, if any should it go to? Currently if it is confirmed, past its notification date and no notification has yet been sent, then and entry norto9fication will be sent.
Is also the separate consideration required for the members who are not required to pay in advance? I can't remember ....

**Comment by asimshah** [comment]
In the light of running without the gateway, can you please describe what you would like the system to do.

**Comment by mikebattye** [comment]
The key issues is Confirmation. If the BS has confirmed a booking whether paid, not paid or 'unpaid' then it should get the notification. This deals with members who do not have top pay in advance as they will autoconfirm and so get the code. Does that make sense?

**Comment by asimshah** [comment]
Well, this is not what the booking flow document says. The BS can Cancel, Approve (for under 18s) or set as Paid - there is no "Confirmation" that the BS can do. So you cannot cause entry code notification to occur for a non-privileged member except by marking the booking as Paid. This means you cannot confirm an non paid booking for a non-privileged member.
Privileged members get an entry notification (when it is due) regardless of whether they have paid or not and the BS cannot do anything about it. If he cancels it after the code has gone out then it is possible that a the punter turns up and uses the hut regardless.

**Comment by mikebattye** [comment]
We can live with that. Hopefully unpaid is a rare event.
