### ISSUE TITLE
Test booking cancelled

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#37]
Test booking made for 1 Aug. Appears in Occupancy but has been auto cancelled.

Email flow looks seriously wrong!

![barney](https://cloud.githubusercontent.com/assets/11847651/16945633/b63f29f4-4d9d-11e6-994d-b59aadd9af6d.PNG)

**Comment by mikebattye** [comment]
Let me check.

**Comment by mikebattye** [comment]
I can't reproduce this.

**Comment by asimshah** [comment]
Then please close this
