### ISSUE TITLE
System Actions EntryNotification

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#41]
What is the time interval for checking system actions? Eg I notice that EntryNotification doesn’t go out at the same time as Confirmed email when the booking is <ECI.

**Comment by asimshah** [comment]
The interval is a little indeterminate. It could be immediately, it could be after a few minutes, it could be early the next day depending on context. Does this matter?

**Comment by mikebattye** [comment]
From admin's point of view probably not. So long as they know it may not be immediate.

**Comment by asimshah** [comment]
is this still an issue?
