### ISSUE TITLE
Booking weekend

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#46]
Trying to book weekend I couldn’t select 12 beds, Putting 12 in the number field did not allow me to move to the next screen. I could only do this by selecting _less than_ 12 beds (of course it then offered me the whole hut which is correct behaviour). I also found some odd behaviour with the 'Back' and 'Next' options. See if you can reproduce the following:

Select a Friday date
Select 1 bed
Next (offered whole hut)
Now try Back
Change to 12 beds
Next no longer works
Change to 1 bed (I deleted the numeric 2)
Next (offered whole hut)
Now Back doesn't work.

**Comment by asimshah** [comment]
I have had a look at this problem and I can see why the errors occur. The fix requires a change to the way that the DWH rules for the whole hut at the weekend are programmed.  In the process, I find that I am not sure that the choices available are actually correct in all circumstances. Remember that apart from the whole hut there are also two rooms of 4 and 8 each - has this feature been thoroughly tested and is it OK?

**Comment by mikebattye** [comment]
I’ll check.

**Comment by mikebattye** [comment]
![image](https://cloud.githubusercontent.com/assets/11847651/24164684/64d0e5c8-0e66-11e7-96a2-30cf6245d34a.png)

I have tried various combinations and the only issue I can see is shown above: it doesn't offer you one room for 8 beds.

**Comment by asimshah** [comment]
This should now be working. If so, please close.
