### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#47]
Can't remember when this was last discussed but, from experience, the only important summary info we need to get from the booking app is number of beds occupied for a given period (e.g. 12 months) and the amount paid. I might also be useful to have totals of members broken down by category. Is that feasible?

**Comment by asimshah** [comment]
As far as  recall, there is no report that is capable of adding anything up (though I might have forgotten!). Consequently, this would be a whole new type of report  and will take some time to add to the architecture...

**Comment by mikebattye** [comment]
Put it on the back burner then.

Regards, Mike

Sent from my iPad

On 21 Mar 2017, at 19:05, asimshah <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as recall, there is no report that is capable of adding anything up (though I might have forgotten!). Consequently, this would be a whole new type of report and will take some time to add to the architecture...

**Comment by asimshah** [comment]
Ok, I am closing this.
