### ISSUE TITLE
Registering with incorrect membership number

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#50]
![image](https://cloud.githubusercontent.com/assets/11847651/24293686/f402bda4-108a-11e7-86d2-cc049b6b61aa.png)

I tried registering a new member carmel.gray@yahoo.com but with another member's number (K340514) - sounds a rather unusual occurrence but it could conceivably happen! I received and internal server error message and the system 'hung' as above. Had to restart the site to continue.

**Comment by asimshah** [comment]
a fix for this is in the next version

**Comment by asimshah** [comment]
The site has now been upgraded for this fix.
