### ISSUE TITLE
Registration Process

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#6]
Users must be registered before a booking can be made.  Will require name, email and dob and activation through email link. However booking calendar can be viewed by all visitors to the site whether logged in or not. 
(from booking app document - 30Jul2015)

**Comment by asimshah** [comment]
The registration form for DWH will ask for:

1. Email Address
1. Password
1. First name
1. Last name
1. Date of birth
1. BMC membership number
1. Club/Organisation

**Comment by asimshah** [comment]
There is also a user profile form where a member can update first and last name.
Should they also be allowed to change the BMC Membership, organisation ? and the date of birth?

**Comment by asimshah** [comment]
Do we need to guarantee that a BMC membership number is only ever used once, i.e. no one can register with a BMC number that has already been used by a previous registration? 

This has a bearing on 
1. Being able to modify the BMC number via the user profile (or not); or the admin modifying the BMC number.
1. Deleting members - I can't remember if this is allowed or not.

**Comment by mikebattye** [comment]
Have to talk that through with you. Most sites allow you to edit everything but email in my experience.


Sent from my Samsung device

-------- Original message --------

**Comment by mikebattye** [comment]
Agreed


Sent from my Samsung device

-------- Original message --------

**Comment by mikebattye** [comment]
As far as individual bookings are concerned then there is no problem - individuals only have one number. However it is possible that a member might make a booking on behalf of more than one organisation. But even here the booking is in there name.
I think you should be able to delete members.


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
Deleting a member will require deleting all bookings made by that member, thus loosing history!

**Comment by mikebattye** [comment]
Then disabling would be better?
