### ISSUE TITLE
Booking Process

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#7]
Booking process (BMC members): Bookings will be accepted provided membership is valid at time of registration.  (This could be a problem if membership lapses but I think we agreed that the system would be much simpler if it worked this way.) For bookings less than 28 days ahead, app will process payment through BMC’s Sage Pay system, and the member will receive automatic confirmation on screen and by email. 

Booking (non members): Where the booking is not made by an individual member (e.g. commercial organisation) there must be some means of overriding the registration/validation process. One way would be the ability of admin (ie Mark) to make a booking on their behalf. Even simpler would be just block the dates as unavailable and take a ‘paper’ booking (though not so good from an accounting/reprting point of view.
(from booking app document - 30Jul2015)

**Comment by asimshah** [comment]
The booking (non members) section is completely meaningless! What - exactly - is the proposal?

**Comment by mikebattye** [comment]
As we discussed over the phone we do let non BMC members book the hut in certain circumstances  (eg Peak park or SWT personel. I thought we came to the view that if this made things too complicated Mark could just block the hut and make a manual record.


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
I am closing this issue and the one about advance booking and opening a new called Booking Process Rules
