### ISSUE TITLE
Advance Booking

### ISSUE THREAD

**Issue by asimshah** [asimshah/booking-app#8]
Advance booking: Bookings more than 28 days in advance do not have to pay at the time of booking. They will also still have the option to pay by cheque etc. In such cases the BMC office will mark the payment ‘Is paid’ as now (this functionality to be made clearer). They will get a reminder a little before the 28 days (7 days?) – if they don’t pay the booking will be automatically cancelled and the hut shown as vacant (they can always rebook if no one else has jumped in in the meantime).

(from booking app document- 30Jul2015)

**Comment by asimshah** [comment]
Is the idea that when making a booking that is less than 28 days in advance, a payment has to be made online for the booking to be made at all?

**Comment by mikebattye** [comment]
I think that follows from what I said. Is 28 days too long? The office would prefer as few cheques or phone payments as possible.


Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
It's a matter of user friendliness, really. When you make a payment online, It can happen that the payment fails (wrong card, expired, not authorised, whatever).

If we refuse to go ahead with the booking under these circumstances, then the entire cycle will have to be repeated. But if that is what you want, OK. I can see that the automatic cancellation feature conflicts with keeping the booking if the payment is not made. So perhaps that is how it will have to work: payment fails, then booking also fails.

**Comment by mikebattye** [comment]
It seems logical to me that the booking fails if the payment does.

Presumably it’s another case where it is reasonable to contact Mark for advice on the assumption that this ia a scenario that wouldn’t happen often.

**Comment by asimshah** [comment]
I am closing this issue and also one called Booking Process #7 and have opened a new called Booking Process Rules #20
